name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "30 02 * * *"   # 8AM IST everyday
    - cron: "00 14 * * *"   # 7:30PM IST everyday
    - cron: "00 06 * * 1-5" # 11:30PM IST Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with: 
          node-version: '22'

      - name: Install newman and html extra globally
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      
      - name: Run the Postman collection with newman
        run: |
          newman run 'InWarrantyFlowCollection.postman_collection.json' \
            -e QA.postman_environment.json \
            -d testdata.csv \
            -r cli,htmlextra

        
                
